[CORE] Add Teslamate integration
flosoft/TeslaETA pull request #35
Opened 2024-07-22 17:21 UTC by Zegorax

Ciao,

Hope you're doing well!

You can find in this PR an integration with Teslamate in addition to Teslalogger. It's using the Factory pattern and interface extensions to have a clean code and working regardless of what the backend provider is.

I made a little modification regarding the distance mechanism. I've changed the check and instead of relying on the distance, it will check whether there is a "fixed" lat/long in the shared link DB (The form allows the creation without one). Therefore, if there is nothing, it will use the destination set in the Tesla.

Feel free to review it and don't hesitate to ask me if you have any question :)

And of course, please test it extensively!

2024-07-23 11:03 UTC, flosoft commented
Awesome stuff! Thanks for your work on this!
I'll give it a test with my TeslaLogger later today and if all works well, I'll merge and build.

2024-07-25 09:55 UTC, flosoft requested changes
2 minor changes, but otherwise looks good to go.

2024-07-25 09:55 UTC, flosoft commented on docker-compose.yml
Let's remove this file. We could instead add a docker-compose.yml.teslamate example including TeslaETA.

2024-07-25 09:55 UTC, flosoft commented on interfaces/backendfactory.py
> +            raise Exception(f"Unknown backend provider : {name}. Available choices are 'teslalogger' or 'teslamagte'.")
typo in here

2024-07-25 10:25 UTC, Zegorax commented on interfaces/backendfactory.py
> +            raise Exception(f"Unknown backend provider : {name}. Available choices are 'teslalogger' or 'teslamagte'.")
Good catch with the typo, will fix it.

2024-07-25 10:26 UTC, Zegorax commented on docker-compose.yml
Indeed, it was used for my development only and got committed by mistake.

2024-08-05 13:27 UTC, merged

2024-08-05 13:42 UTC, Zegorax commented
Sorry I just received the notification about it being merged. Thanks!